import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import React, { useEffect, useState } from "react";
import Link from "next/link";

import html from "../public/assets/experience/html.png";
import css from "../public/assets/experience/css.png";
import javascript from "../public/assets/experience/javascript.png";
import reactImage from "../public/assets/experience/react.png";
import nextjs from "../public/assets/experience/nextjs.png";
import tailwind from "../public/assets/experience/html.png";
import graphql from "../public/assets/experience/graphql.png";
import node from "../public/assets/experience/node.png";
// import components
import Portfolio from "../components/Portfolio";
import Experience from "../components/Experience";
import Contact from "../components/Contact";
import About from "../components/About";

import {
  FaBars,
  FaTimes,
  FaFacebook,
  FaGithub,
  FaTwitter,
  FaLinkedin,
} from "react-icons/fa";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const experiences = [
    {
      id: 1,
      title: "HTML",
      src: html,
    },
    {
      id: 2,
      title: "CSS",
      src: css,
    },
    {
      id: 3,
      title: "JavaScript",
      src: javascript,
    },
    {
      id: 4,
      title: "React",
      src: reactImage,
    },
    {
      id: 5,
      title: "Next JS",
      src: nextjs,
    },
    {
      id: 6,
      title: "Tailwind",
      src: tailwind,
    },
    {
      id: 7,
      title: "GraphQL",
      src: graphql,
    },
    {
      id: 8,
      title: "Node JS",
      src: node,
    },
  ];

  const [navigation, setNavigation] = useState(false);
  const [pageScroll, setPageScroll] = useState(false);

  useEffect(() => {
    const sub = window.addEventListener("scroll", () =>
      setPageScroll(window.scrollY >= 90)
    );

    return sub;
  }, []);

  const links = [
    {
      id: 1,
      link: "home",
    },
    {
      id: 2,
      link: "portfolio",
    },
    {
      id: 3,
      link: "experience",
    },
    {
      id: 4,
      link: "me",
    },
    {
      id: 5,
      link: "contact",
    },
  ];

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Luca Stringhetti Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* NAVBAR SECTION */}
      <nav className=" mb-12 flex dark:text-white">
        <div
          className={`w-screen h-20 z-10 fixed bg-white text-black duration-300 ease-in ${
            pageScroll && "bg-black text-[#fff]"
          }`}
        >
          <div className="flex justify-between items-center w-full h-full max-w-screen-xl mx-auto p-4">
            <Link href="/#home">
              <h1 className="text-3xl lg:text-4xl font-bold uppercase underline underline-offset-2 tracking-wider cursor-pointer">
                Luca Stringhetti
              </h1>
            </Link>

            <div>
              <ul className="hidden md:flex">
                {links.map(({ id, link }) => (
                  <Link key={id} href={`/#${link}`}>
                    <li className="ml-10 text-sm uppercase cursor-pointer duration-200 ease-out hover:scale-105 tracking-wider">
                      {link}
                    </li>
                  </Link>
                ))}
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl ml-10"
                />
              </ul>

              {!navigation && (
                <div
                  className="md:hidden cursor-pointer"
                  onClick={() => setNavigation(true)}
                >
                  <FaBars size={30} />
                </div>
              )}
            </div>
          </div>

          <div
            className={
              navigation
                ? "md:hidden fixed left-0 top-0 w-full h-full bg-black/70 backdrop-blur"
                : ""
            }
          >
            <div
              className={
                navigation
                  ? "fixed left-0 top-0 w-4/5 h-full bg-gradient-to-r from-blue-600 to-cyan-600 text-white p-10 ease-in duration-500"
                  : "fixed top-0 left-[-100%] p-10 h-full ease-in duration-500"
              }
            >
              <div>
                <div className="flex w-full items-center justify-between">
                  <Link href="/#home">
                    <h2
                      onClick={() => setNavigation(false)}
                      className="text-3xl font-bold uppercase underline underline-offset-2 tracking-wider cursor-pointer"
                    >
                      Luca Stringhetti
                    </h2>
                  </Link>
                  <div
                    onClick={() => setNavigation(false)}
                    className="p-3 cursor-pointer"
                  >
                    <FaTimes size={30} />
                  </div>
                </div>
              </div>

              <div className="mt-24 flex flex-col h-fit gap-20">
                <ul className="uppercase">
                  {links.map(({ id, link }) => (
                    <Link key={id} href={`/#${link}`}>
                      <li
                        onClick={() => setNavigation(false)}
                        className="py-4 text-2xl tracking-wider cursor-pointer"
                      >
                        {link}
                      </li>
                    </Link>
                  ))}
                 
                </ul>

                <div>
                  <div className="grid grid-cols-1 mx-auto w-4/5 gap-10">
                    <div className="flex items-center justify-center rounded-full shadow-md shadow-white p-3 cursor-pointer">
                      <FaLinkedin size={25} />
                    </div>
                    <div className="flex items-center justify-center rounded-full shadow-md shadow-white p-3 cursor-pointer">
                      <FaGithub size={25} />
                    </div>
                    <div className="flex items-center justify-center rounded-full shadow-md shadow-white p-3 cursor-pointer">
                    <BsFillMoonStarsFill size={25}
                      onClick={() => setDarkMode(!darkMode)}
                      className=" cursor-pointer text-2xl"
                    />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          {/* NAVBAR SECTION */}
          {/* <nav className=" mb-12 flex dark:text-white"> */}

          {/* <h1 className="text-xl font-burtons">developedbyLS</h1>

            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul> */}
          {/* </nav> */}

          {/* ABOUT SECTION */}
          <About />
        </section>

        {/* SKILL SECTION */}
        <section>
          <Experience />
        </section>

        {/* PORFOLIO SECTION */}
        <section className="py-10">
          <Portfolio />
        </section>

        {/* CONTACT FORM */}
        <section className="">
          <Contact />
        </section>
      </main>
    </div>
  );
}
