import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import { useState } from "react";

import html from "../public/assets/experience/html.png";
import css from "../public/assets/experience/css.png";
import javascript from "../public/assets/experience/javascript.png";
import reactImage from "../public/assets/experience/react.png";
import nextjs from "../public/assets/experience/nextjs.png";
import tailwind from "../public/assets/experience/html.png";
import graphql from "../public/assets/experience/graphql.png";
import node from "../public/assets/experience/node.png";
// import components
import Portfolio from "../components/Portfolio";
import Experience from "../components/Experience";
import Contact from "../components/Contact";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const experiences = [
    {
      id: 1,
      title: "HTML",
      src: html,
    },
    {
      id: 2,
      title: "CSS",
      src: css,
    },
    {
      id: 3,
      title: "JavaScript",
      src: javascript,
    },
    {
      id: 4,
      title: "React",
      src: reactImage,
    },
    {
      id: 5,
      title: "Next JS",
      src: nextjs,
    },
    {
      id: 6,
      title: "Tailwind",
      src: tailwind,
    },
    {
      id: 7,
      title: "GraphQL",
      src: graphql,
    },
    {
      id: 8,
      title: "Node JS",
      src: node,
    },
  ];

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Luca Stringhetti Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">developedbyLS</h1>

            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
    
          <div className="text-center p-10">
            <h2 className="py-2 text-blue-600 dark:text-teal-400 text-5xl md:text-7xl tracking-wider uppercase font-bold text-center">
              Luca Stringhetti
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Web Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto">
              A driven full-stack developer with a passion for creating
              intuitive and impactful web applications. With a background in
              customer service management, I bring a unique perspective to my
              work, honing strong problem-solving and communication skills.
              After completing a full-stack coding bootcamp, I am eager to apply
              my technical knowledge and drive to real-world projects. My goal
              is to use my skills to create user-centered digital solutions that
              make a meaningful impact.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/lucastringhetti/">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Quantumminded">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b dark:from-teal-500 from-blue-600 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        {/* SKILL SECTION */}
        <section>
          <Experience />
        </section>

        {/* PORFOLIO SECTION */}
        <section className="py-10">
          <Portfolio />
        </section>

        {/* CONTACT FORM */}
        <section className="">
          <Contact />
        </section>

      </main>
    </div>
  );
}
